import jsPDF from "jspdf";
import * as XLSX from "xlsx";

interface ExportData {
  calculatorName: string;
  calculatorType: string;
  inputs: Record<string, unknown>;
  result: Record<string, unknown>;
}

const formatValue = (value: unknown): string => {
  if (value === null || value === undefined) return "-";
  if (typeof value === "number") {
    return value.toLocaleString("en-US", { maximumFractionDigits: 2 });
  }
  if (typeof value === "boolean") return value ? "Yes" : "No";
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
};

const formatKey = (key: string): string => {
  return key
    .replace(/([A-Z])/g, " $1")
    .replace(/_/g, " ")
    .replace(/^./, (str) => str.toUpperCase())
    .trim();
};

export const exportToPDF = (data: ExportData): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;
  const lineHeight = 8;
  const margin = 20;

  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("CalcBrew", margin, yPos);
  
  yPos += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("Calculation Report", margin, yPos);
  
  // Date
  doc.text(new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit"
  }), pageWidth - margin, yPos, { align: "right" });

  yPos += 15;
  doc.setTextColor(0);

  // Calculator name
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(data.calculatorName, margin, yPos);
  
  yPos += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Category: ${formatKey(data.calculatorType)}`, margin, yPos);
  doc.setTextColor(0);

  yPos += 15;

  // Divider line
  doc.setDrawColor(200);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // Inputs section
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Input Values", margin, yPos);
  yPos += lineHeight;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  
  Object.entries(data.inputs).forEach(([key, value]) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    const label = formatKey(key);
    const formattedValue = formatValue(value);
    doc.text(`${label}:`, margin, yPos);
    doc.text(formattedValue, margin + 60, yPos);
    yPos += lineHeight;
  });

  yPos += 10;

  // Divider line
  doc.setDrawColor(200);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // Results section
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Results", margin, yPos);
  yPos += lineHeight;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  
  Object.entries(data.result).forEach(([key, value]) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    const label = formatKey(key);
    const formattedValue = formatValue(value);
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, margin, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(formattedValue, margin + 60, yPos);
    yPos += lineHeight;
  });

  // Footer
  yPos = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by CalcBrew Pro", margin, yPos);
  doc.text("calcbrew.com", pageWidth - margin, yPos, { align: "right" });

  // Save the PDF
  const fileName = `${data.calculatorName.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(fileName);
};

export const exportToExcel = (data: ExportData): void => {
  // Create workbook
  const wb = XLSX.utils.book_new();

  // Prepare data for the sheet
  const sheetData: (string | number)[][] = [];

  // Header
  sheetData.push(["CalcBrew - Calculation Report"]);
  sheetData.push(["Calculator", data.calculatorName]);
  sheetData.push(["Category", formatKey(data.calculatorType)]);
  sheetData.push(["Date", new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit"
  })]);
  sheetData.push([]);

  // Inputs section
  sheetData.push(["INPUT VALUES"]);
  sheetData.push(["Field", "Value"]);
  
  Object.entries(data.inputs).forEach(([key, value]) => {
    sheetData.push([formatKey(key), formatValue(value)]);
  });

  sheetData.push([]);

  // Results section
  sheetData.push(["RESULTS"]);
  sheetData.push(["Field", "Value"]);
  
  Object.entries(data.result).forEach(([key, value]) => {
    sheetData.push([formatKey(key), formatValue(value)]);
  });

  // Create worksheet
  const ws = XLSX.utils.aoa_to_sheet(sheetData);

  // Set column widths
  ws["!cols"] = [{ wch: 30 }, { wch: 40 }];

  // Add worksheet to workbook
  XLSX.utils.book_append_sheet(wb, ws, "Calculation");

  // Save the file
  const fileName = `${data.calculatorName.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.xlsx`;
  XLSX.writeFile(wb, fileName);
};
